Repository jokourno12/TradeSphere, pull requests merged in 2024-03, with the labels that each got.

#1 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#2 Service
  src/main/java/com/tradesphere/app/service/UserService.java
Labels: enhancement

#3 feat: init security
  pom.xml
  src/main/java/com/tradesphere/app/security/AuthTokenFilter.java
  src/main/java/com/tradesphere/app/security/JwtUtil.java
  src/main/java/com/tradesphere/app/security/PasswordConfiguration.java
  src/main/java/com/tradesphere/app/security/SecurityConfiguration.java
  src/main/resources/application.properties
Labels: enhancement, blocked, needs investigation

#5 Feat(auth) gagas
  src/main/java/com/tradesphere/app/constant/EGender.java
  src/main/java/com/tradesphere/app/constant/ERole.java
  src/main/java/com/tradesphere/app/model/entity/Admin.java
  src/main/java/com/tradesphere/app/model/entity/AppUser.java
  src/main/java/com/tradesphere/app/model/entity/Role.java
  src/main/java/com/tradesphere/app/model/entity/Trader.java
  src/main/java/com/tradesphere/app/model/entity/User.java
  src/main/java/com/tradesphere/app/security/AuthTokenFilter.java
  src/main/java/com/tradesphere/app/security/JwtUtil.java
  src/main/java/com/tradesphere/app/security/SecurityConfiguration.java
  src/main/java/com/tradesphere/app/service/UserService.java
Labels: enhancement, blocked, needs investigation
